tailscale/rootfs/etc/services.d/tailscaled/post
If forwarding for ipv4 or ipv6 is disabled, routes for those address families will not be advertised
=> :shirt: Skip address family from route advertisement if it has forwarding disabled

tailscale/rootfs/etc/services.d/tailscaled/run
As discussed in #22 #32 this plugin is currently not able to correctly route local traffic. If understood the docs correctly if it is running in a container (as it does in this plugin) it needs to set this, to be able to keep iptables between host and container in sync. Otherwise local routing will not work correctly.
More on this here:
- https://github.com/tailscale/tailscale/issues/504
- https://tailscale.com/kb/1112/userspace-networking/
I've successfully tested this with my setup and I can access all the local IPs (like 192.168.1.*) in my network. Of course Subnets need to be enabled from Tailscale admin panel. Furthermore, this PR bumps the tailscale version.
I have a working repository with these changes so anyone can test easily: https://github.com/moritzgloeckl/addon-tailscale
=> Add Userspace networking mode flag

tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.28.0
https://github.com/tailscale/tailscale/releases/tag/v1.30.0
https://github.com/tailscale/tailscale/releases/tag/v1.30.1
Supersedes https://github.com/hassio-addons/addon-tailscale/pull/106
=> ⬆️ Upgrade Tailscale to 1.30.1

tailscale/DOCS.md, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
PR #130 precedes this PR
See commits:
- fix: jq: error (at <stdin>:1): Cannot iterate over null (null)
- fix: unnecessary "true" or "false" log entry
=> Minor bugfixes

tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Bugfix.
Line:
```
./post &
```
Causing error:
```
./run: line 19: ./post: No such file or directory
```
This script already got a standalone, oneshot "post-tailscaled" service.
-
=> Bugfix in migrated S6 scripts

tailscale/build.yaml, tailscale/config.yaml
This reverts commit fa78fb76f07e93af143b42838054e4c66d997626.
We can't move away just yet, as the Supervisor currently prevents this.
=> Revert "🗑️  Move away from Codenotary (#162)"

tailscale/DOCS.md, tailscale/Dockerfile, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Tailscaled is quite chatty and emits a really large amount of log messages.
This PR disables these messages after 200 lines, but makes it possible to re-enable the full logging for troubleshooting.
Based on the idea from https://github.com/tailscale/tailscale-synology/pull/110
--
=> Suppress tailscaled logs after 200 lines

tailscale/DOCS.md
Based on Tailscale's recommendation it is better to disable key expiry on servers/IoT devices. Without regular reauthentication users can loose connection to their devices permanently.
=> Extend documentation with disabling key expiry

tailscale/config.yaml
In PR #41 tailscaled moved on to userspace-networking, though the add-on privileges required for tun remained in the config.yaml.
=> Remove unneeded add-on privileges

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/translations/en.yaml
Adds support for setting a custom control server (e.g., a self-hosted Headscale instance).
supersedes and closes #175
=> Add custom control server support

tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Fix typo when adding a custom login_server.
```
/etc/s6-overlay/s6-rc.d/post-tailscaled/run: line 28: login_server: unbound variable
```
#180
=> Fix typo "login_server: unbound variable"

tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
It should have been `login-server` instead of `login_server`.
Tested this and works fine now.
=> Fix login-server option

tailscale/DOCS.md
PR #185 didn't add taildrop to the example config in the DOCS.
Also PR #180 moved the tags config to the end in the description, but not in the example config.
=> Add taildrop to example configuration

tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/translations/en.yaml
Adds the option to disable accepting MagicDNS. This might be helpful/needed when the user runs things like Pi-hole/AdGuard on the same machine.
A user can still use MagicDNS in such cases, by pointing their DNS server to `100.100.100.100` (and `fd7a:115c:a1e0::53`).
=> Make accepting magicDNS optional

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/type, tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/up, tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh, tailscale/translations/en.yaml
Replaces PR #89 #134
This is a better solution to the #62 issue than #89 #134 because it doesn't need any manual configuration and also provides a built-in proxy for the https traffic. We don't need to refresh the certificates manually, this is all done by tailscale automatically.
Fixes #62
=> Enable Tailscale's builtin inbound HTTPS proxy

tailscale/rootfs/etc/nginx/templates/ingress.gtpl
Modify nginx ingress JS replacement for rendered tailscale link pages to provide fallback on mobile for target=_blank links. 
On iOS mobile, error page currently appears when clicking link to Tailscale.  
If link fails to open, falls back to displaying URL to be copy-pasted into browser.
- fixes https://github.com/hassio-addons/addon-tailscale/issues/157
- fixes https://github.com/hassio-addons/addon-tailscale/issues/258
=> Create fallback page for iOS browsers failing to open Tailscale login page

tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/taildrop/run
Minor code quality improvement.
The `proxy` and `taildrop` services are waiting for `post-tailscaled`, so move the status checks from the beginning of `proxy` and `taildrop` to the end of `post-tailscaled`.
=> Remove duplicate status checks from dependent S6 services

tailscale/DOCS.md, tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Don't use `--no-logs-no-support` option when the add-on's log level is debug, to prevent _"Failed Operation: backend error: tailnet requires logging to be enabled. Remove --no-logs-no-support from tailscaled command line."_ errors when users enable flow logging in their tailnet.
fixes #211
=> Do not opt out of client log upload in debug log level

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/type, tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/up, tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh, tailscale/translations/en.yaml
Note: this is based on / continuation of #196, but I will rebase this PR as required.
As an addition to the inbound HTTPS proxy, this enables Tailscale's Funnel.
Similarly to the HTTPS proxy, this currently works only on port 443 and only for HA access. This can be later modified when Tailscale's WEB-UI will provide some configuration options.
=> Enable Tailscale's Funnel feature

tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
Status JSON has changed. Requires Tailscale v1.50.0 or later.
=> Use new .Self.CapMap in status JSON for HTTPS support check

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/translations/en.yaml
This is needed in some scenarios, such as when the other node is advertising the subnet that home assistant is on.
=> make accepting subnet routes optional

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run, tailscale/translations/en.yaml
Note: this is based on / continuation of #196, but I will rebase this PR as required.
The currently unreleased #181 dropped userspace networking automatically.
I've merged it into my fork, and 1 user complained, that his host lost all network access (even local 192.168.x.x did not worked). ***UPDATE:*** _The reason must be that the same subnet is advertised at multiple locations and it caused collision. The PR #201 provides a possible solution for collision, but I think making userspace-networking configurable still makes sense._
This PR makes it configurable, by default the add-on still uses userspace networking, but if somebody adds `userspace_networking: false` to the configuration, it will drop it and create the `tailscale0` interface with all of the dangers of it. 
But at least it …
=> Make userspace networking configurable

tailscale/DOCS.md, tailscale/Dockerfile, tailscale/config.yaml, tailscale/rootfs/etc/NetworkManager/dispatcher.d/connectivity-change, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/finish, tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/type, tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh, tailscale/rootfs/usr/bin/protect-subnet-routes, tailscale/rootfs/usr/bin/subnet-routes, tailscale/rootfs/usr/bin/unprotect-subnet-routes
Note: this is based on / continuation of #199, but I will rebase this PR as required.
TLDR:
- when tailscaled starts: `ip rule add to "${route}" priority 5000 table main` for each advertised local subnets
- when stops: `ip rule del to "${route}"` for each previously added subnets
- when nm-dispatcher notifies about networking config change: delete rules and recalculate again
Idea is stolen from: https://github.com/tailscale/tailscale/issues/6231#issuecomment-1418124609 (Workaround 3)
Reason: Tailscale adds it's own routes with higher priority than the "normal" route settings, so we add back the local subnets with even higher priority. Tailscale wants to forward the local domain in case it is a coffee shop WiFi that collides with our tailnet settings, but in a server's case, it causes …
=> Protect local subnets from being routed toward Tailscale subnets if they collide

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/rootfs/usr/bin/subnet-routes, tailscale/translations/en.yaml
Note: this is based on / continuation of #201, but I will rebase this PR as required.
Make it possible to advertise not only the default routes on the managed interfaces, but user defined routes also, to support advanced networking situations (like site-to-site networking with multiple subnets, traverse multiple networks, etc.).
=> Make advertise routes configurable

tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/down, tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/finish, tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/type, tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/up, tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
Note: this is based on / continuation of #201, but I will rebase this PR as required.
In case of non userspace networking, clamp the MSS to the MTU for all advertised subnet's interface. Eg:
```
iptables -t mangle -A FORWARD -i tailscale0 -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```
If user later enables subnet routing (for site-to-site networking), these settings are already there. Until eg. tailscale0->eth0 routing is not used, there is no traffic to apply these settings on, they make no harm.
Source: https://tailscale.com/kb/1214/site-to-site/ Step 1 / Point 4
Even LAN->tailnet->LAN site-to-site networking works without these clamping, but tailscale supports insists on to do it.
=> Clamp the MSS to the MTU for all advertised subnet's interface

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/translations/en.yaml
Makes possible to fully utilize site-to-site networking, allows to disable source NAT for subnet devices.
Source: https://tailscale.com/kb/1214/site-to-site/ Step 1 / Point 2
=> Make subnet source NAT configurable

tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/rootfs/usr/bin/protect-subnet-routes, tailscale/rootfs/usr/bin/subnet-routes
Fixes a logical bug in #201: That PR protected the ***advertised*** subnets, what was originally identical with the ***local*** subnets, but after the advertised subnets are user configurable, I think the subnet protection logic should always protect ***local*** subnets, independently of what users configured to be advertised. Because collisions will be between local and accepted routes not between advertised and accepted.
**Note:** There is another possible improvement, but that is not addressed by this PR: We protect subnet domains, maybe should only protect HA's local IPs only. But I'm not sure whether it solves or creates more problems. Until there is some concrete need for it, I prefer not to modify the current logic.
=> Fix local subnet protection

tailscale/rootfs/usr/bin/protect-subnet-routes
Just a small improvement.
Currently it waits only 30s, but after a SU update the restart can take easily 10 seconds, so increase it from 30 (15 x 2s) to 90s (18 x 5s).
```
[14:45:36] INFO: Removing route 192.168.1.0/24 from ip rules
[14:45:37] INFO: Waiting for the supervisor to be ready...
[14:45:40] INFO: Waiting for the supervisor to be ready...
[14:45:42] INFO: Waiting for the supervisor to be ready...
[14:45:44] INFO: Supervisor is ready
[14:45:45] INFO: Adding local subnets to ip rules with higher priority than Tailscale's routing,
```
=> Increase wait time for Supervisor

.github/renovate.json, tailscale/Dockerfile
Base image v15 also bumped alpine version.
Also remove ip6tables reference, because it is part of the plain iptables from v3.19.
=> Cleanup ip6tables

tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/finish, tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run
Bugfix: Clamping was done for IPv4 only, this adds it for IPv6 traffic also.
=> Clamp the MSS for IPv6 also

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/serve/run, tailscale/translations/en.yaml
Also made the port configurable. Proxy and Funnel are using the same port, so making 2 port configs and dropping the current `proxy: bool?` and `funnel: bool?` configs can't be done. So 443 by default is configured as port, but this won't start proxy or funnel automatically.
fixes #276
=> Make Proxy and Funnel port configurable

tailscale/config.yaml
Though this way it is easier to enter a wrong value, like 444, but this will give an error in the UI at least.
With this modification the value won't be inside a `"..."` in the YAML.
Follow up on #277
=> Use regex for Proxy and Funnel port configuration validation

tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run, tailscale/rootfs/usr/bin/kernel-config, tailscale/rootfs/usr/bin/protect-subnet-routes
In case of Debian/Supervised installations use `cat /boot/config-$(uname -r)` instead of `zcat /proc/config.gz`
fixes #325 #316
=> Fix kernel configuration access for Debian Supervised installations

tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run, tailscale/rootfs/usr/bin/kernel-config, tailscale/rootfs/usr/bin/protect-subnet-routes
Drop accessing `/boot/config-$(uname -r)` or `/proc/config.gz`:
- It was placed there mainly because some of the HA OS images had different routing capabilities, but it was already fixed by the OS team (see https://github.com/home-assistant/operating-system/issues/3026 and https://github.com/home-assistant/operating-system/pull/3027).
- The other kernel config check is TCPMSS related, but that results only in a warning, so we can test whether that TCPMSS manipulation fails and emit a warning then, and do not check the kernel config in advance.
really fixes #325
=> Drop kernel configuration access

tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
Minor code quality improvement. No functional change.
Use `web` as `file`, `up`, `serve`, etc.
=> Use web as a command, not as an option

tailscale/DOCS.md, tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
Until tailscale webui doesn't make available most of the add-on config options, it is better to make it readonly. If it is not readonly, changed values will be lost after the next add-on restart.
closes #314
=> Use readonly webui mode in v1.60

tailscale/Dockerfile, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Noticed a warning in the tailscale logs:
```
Warning: UDP GRO forwarding is suboptimally configured on enu1u1, UDP forwarding throughput capability will increase with a configuration change.
See https://tailscale.com/s/ethtool-config-udp-gro
```
The suggested change at https://tailscale.com/s/ethtool-config-udp-gro basically turns on the rx-udp-gro-forwarding feature.
Smoke tested on: HA OS (armv7l, aarch64, x86_64 (VM)), Supervised (x86_64 (VM))
--
=> Linux optimizations for subnet routers and exit nodes

tailscale/DOCS.md, tailscale/config.yaml, tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run, tailscale/translations/en.yaml
Add `advertise_connector` option to support the `--advertise-connector` flag to use the [app connectors feature](https://tailscale.com/kb/1281/app-connectors).
I couldn't find the option available in this add-on and wanted to try it out. Tested this feature locally and it's working great.
N/A
=> Add app connector option
