- tailscale/Dockerfile
- tailscale/rootfs/etc/services.d/tailscaled/post
Fixes network calculation for advertising as routes
> 🚑 Fix network calculation

- tailscale/DOCS.md
Adds a little more information to the documentation on the fact you'll need a Tailscale account.
> 📚Add Tailscale account instructions to documentation

- tailscale/Dockerfile
> 🚑 Use netfilter for IPv6

- tailscale/rootfs/etc/services.d/tailscaled/post
Or else we might invoke the next commands too early.
> 🚑 Wait for tailscale unix socket to become available

- tailscale/rootfs/etc/services.d/tailscaled/run
Finished manual testing, and noticed it wasn't working... wrong filename 😬
> 🚑 Let actually run the post connect script

- README.md
i386 is a supported architecture by this add-on.
> 📚 Adjust i386 badge, as that is a supported architecture

- tailscale/config.json
Because well.. the Docker icon isn't really fitting...
> 💄 Update sidebar icon from Docker -> VPN

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.14.0
> ⬆️ Upgrades Tailscale to 1.14.0

- tailscale/Dockerfile
**Should** fix (needs more testing) #12, at least it fixes the error message :)
> 🚑 Use netfilter for iptables

- tailscale/rootfs/etc/services.d/tailscaled/post
Skip local link addresses/networks when advertising routes.
closes #9
> :shirt: Skip local link addresses in routes advertisement

- tailscale/Dockerfile
Upgrade Tailscale to the v1.14.3 release
https://github.com/tailscale/tailscale/releases/tag/v1.14.3
> Upgrade to Tailscale v1.14.3

- tailscale/Dockerfile
- tailscale/build.yaml
Upgrades add-on base image to 10.2.2
> ⬆️ Upgrades add-on base image to 10.2.2

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.16.0
https://github.com/tailscale/tailscale/releases/tag/v1.16.1
https://github.com/tailscale/tailscale/releases/tag/v1.16.2
> ⬆️ Upgrades Tailscale to 1.16.2

- tailscale/Dockerfile
> ⬆️ Upgrades nginx to 1.20.2-r0

- tailscale/Dockerfile
- tailscale/build.yaml
Upgrades add-on base image to 10.2.3
> ⬆️ Upgrades add-on base image to 10.2.3

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.18.0
> ⬆️ Upgrades Tailscale to 1.18.0

- tailscale/DOCS.md
- tailscale/config.yaml
- tailscale/rootfs/etc/services.d/tailscaled/post
Add support for setting custom ACL tags on the Tailscale instance
closes #53
> Add support for setting ACL tags

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.18.1
> ⬆️ Upgrades Tailscale to 1.18.1

- tailscale/Dockerfile
- tailscale/build.yaml
Upgrades add-on base image to 11.0.0
> ⬆️ Upgrades add-on base image to 11.0.0

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.18.2
> ⬆️ Upgrades Tailscale to 1.18.2

- LICENSE.md
- README.md
- tailscale/.README.j2
- tailscale/DOCS.md
> :fireworks: Updates maintenance/license year to 2022

- tailscale/Dockerfile
- tailscale/build.yaml
Upgrades add-on base image to 11.0.1
> ⬆️ Upgrades add-on base image to 11.0.1

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.20.0
> ⬆️ Upgrades Tailscale to 1.20.0

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.20.1
> ⬆️ Upgrades Tailscale to 1.20.1

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.20.2
fixes #71
> ⬆️ Upgrades Tailscale to 1.20.2

- README.md
- tailscale/.README.j2
- tailscale/DOCS.md
Minor error fix in documentation within About section of README
> Minor fix in About section of README

- tailscale/Dockerfile
Instead of creating an issue with "hey, please update to the latest version", I decided to create this PR ;-) 
* According to https://tailscale.com/changelog/ the DNS lookups via an exit node in many cases have been improved
> ⬆️ Upgrades Tailscale to 1.20.4

- tailscale/Dockerfile
Updates Tailscale to version 1.22.0
Changelog: https://tailscale.com/changelog/
> ⬆️ Upgrades Tailscale to 1.22.0

- tailscale/Dockerfile
- tailscale/build.yaml
Upgrades add-on base image to 11.1.0
> ⬆️ Upgrades add-on base image to 11.1.0

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.22.1
> ⬆️ Upgrades Tailscale to 1.22.1

- .github/workflows/deploy.yaml
- tailscale/build.yaml
- tailscale/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

- tailscale/Dockerfile
https://github.com/tailscale/tailscale/releases/tag/v1.22.2
> ⬆️ Upgrades Tailscale to 1.22.2

- tailscale/Dockerfile
> ⬆️ Upgrades nginx to 1.20.2-r1

- tailscale/Dockerfile
- tailscale/build.yaml
Upgrades add-on base image to 11.1.2
> ⬆️ Upgrades add-on base image to 11.1.2

- tailscale/Dockerfile
- tailscale/build.yaml
- tailscale/rootfs/etc/cont-init.d/nginx.sh
- tailscale/rootfs/etc/services.d/nginx/finish
- tailscale/rootfs/etc/services.d/nginx/run
- tailscale/rootfs/etc/services.d/tailscaled/finish
- tailscale/rootfs/etc/services.d/tailscaled/post
- tailscale/rootfs/etc/services.d/tailscaled/run
- tailscale/rootfs/etc/services.d/web/finish
- tailscale/rootfs/etc/services.d/web/run
Upgrades add-on base image to 12.0.0
> ⬆️ Upgrades add-on base image to 12.0.0

- tailscale/DOCS.md
Making it just a little bit easier to find the add-on
> :books: Use new My Home Assistant link format

- tailscale/Dockerfile
<https://github.com/tailscale/tailscale/releases/tag/v1.26.0>
> ⬆️ Upgrades Tailscale to 1.26.0

- tailscale/rootfs/etc/services.d/tailscaled/post
From console: `unexpected non-flag arguments to 'tailscale status'`
> :ambulance: Fix unexpected non-flag arguments to tailscale

- tailscale/Dockerfile
> ⬆️ Upgrade nginx to 1.22.0-r1

- .github/dependabot.yaml
- .github/renovate.json
- tailscale/Dockerfile
> Add Renovate for dependency management

- LICENSE.md
- README.md
- tailscale/.README.j2
- tailscale/DOCS.md
> :fireworks: Updates maintenance/license year to 2023

- tailscale/DOCS.md
> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> Fix broken URL

- tailscale/build.yaml
- tailscale/config.yaml
Moving away from Codenotary as a signing service.
> 🗑️  Move away from Codenotary

- tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
> Tiny code styling changes

- tailscale/translations/en.yaml
Adds translations, which are used by HA to render the control/UI nicely.
> Add translations

- tailscale/DOCS.md
- tailscale/config.yaml
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
- tailscale/translations/en.yaml
Adds the optional configuration of explicitly enable/disable exit node advertisements.
> Make exit node advertisement configurable

- tailscale/DOCS.md
- tailscale/Dockerfile
- tailscale/config.yaml
- tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
- tailscale/translations/en.yaml
SSIA, provides to option to back out of using Taildrop with this add-on.
> Make Taildrop configurable

- tailscale/DOCS.md
A small update from @nmcc1212
With the new Tailscale pricing you can now have 100 devices on a free account. https://tailscale.com/pricing/
> Device limit update in DOCS.md

- tailscale/config.yaml
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Drops userspace networking.
Needs:
- https://github.com/home-assistant/supervisor/pull/4242
- https://github.com/frenck/action-addon-linter/pull/137
> Drop userspace networking

- tailscale/DOCS.md
> Add docs for accept_dns

- README.md
Fix a link to the `CONTRIBUTING.md` in the readme file.
> Fix CONTRIBUTING Link in README.md

- tailscale/DOCS.md
- tailscale/config.yaml
- tailscale/translations/en.yaml
> Rearrange proxy documentation into alphabetical order

- tailscale/DOCS.md
Some services are starting after a successful login (eg. taildrop, proxy), and users should check the logs again after login, that these services are started successfully also.
Also added a step to check HA configuration for proxy function before starting the add-on. This is important, because without proper `trusted_proxies` configuration, the add-on won't work.
> Update Installation section in documentation

- tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/finish
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/taildrop/finish
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/finish
- tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/finish
> Remove unused variable

- LICENSE.md
- README.md
- tailscale/.README.j2
- tailscale/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
> Fix indentation

- LICENSE.md
- README.md
- tailscale/.README.j2
- tailscale/DOCS.md
> :fireworks: Updates maintenance/license year to 2025
